### ISSUE TITLE
Req: Ability to import into Flex Table

### ISSUE THREAD

**Issue by gridlockjoe** [parvez/network_scanner#1]
Do you know a way I could get this into [Flex Table](https://github.com/custom-cards/flex-table-card)? If the devices could be broken out into individual entities it would be quite easy.

**Comment by parvez** [comment]
In the context of the flex-table-card for Home Assistant, the prop field in the configuration directly references the attributes of the entity specified in the entities section. I believe the flex-table-card automatically handles the mapping between the entity's attributes and the columns in the table.

```
type: 'custom:flex-table-card'
title: Devices
entities:
  include: sensor.network_scanner
columns:
  - name: IP Address
    prop: ip
  - name: MAC Address
    prop: mac
  - name: Custom Name
    prop: name
  - name: Custom Description
    prop: type
  - name: Hostname
    prop: hostname
  - name: Vendor
    prop: vendor
```

**Comment by gridlockjoe** [comment]
Tried this and one row populates with "undefinedundefinedundefined" in each column, except "Network Scanner" is in the Custom Name column.

**Comment by parvez** [comment]
I am unable to test it out using it. It might be complex to get the plugin to work with the data. Not sure if someone else could help you with this. I preferred markdown as it gave me pretty good control.

**Comment by gridlockjoe** [comment]
```
type: custom:flex-table-card
title: Devices
entities:
  include: sensor.network_scanner
columns:
  - name: IP Address
    data: devices
    modify: x.ip
  - name: MAC Address
    data: devices
    modify: x.mac
  - name: Custom Name
    data: devices
    modify: x.name
  - name: Custom Description
    data: devices
    modify: x.type
  - name: Hostname
    data: devices
    modify: x.hostname
  - name: Vendor
    data: devices
    modify: x.vendor
```
