### ISSUE TITLE
How to reconfigure?

### ISSUE THREAD

**Issue by Framstag** [parvez/network_scanner#14]
I initialized the scanner for my network.

A while later I wanted to add configurations for matching macs to custom name and vendor. 

However it seems, I cannot get back to the configuraton dialog (only add a new configuration for the same network which doe snot make much sense)? 

Can I add mapping manually to the configuration.yaml? How woul dbe the syntax?

**Comment by parvez** [comment]
Yes, you can add to configuration yaml in this format

```
network_scanner:
  ip_range: "10.100.1.1-255"
  mac_mapping_1: "bc:14:14:f1:81:1b;Brother Printer;Cloud Network Technology Singapore Pte. Ltd."
  mac_mapping_2: "b1:81:11:31:a1:b1;My iPhone;Apple Inc."
```
